spring:
  application:
    name: dans-auth
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dans_auth
    username: postgres
    password: p@ssw0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /rest/api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 7070
  servlet:
    context-path: /
auth:
  client-secret: s3cR3tK3y